[HotFix] [No Ticket] Ignore "REMOTE_USER" from Shibboleth
CenterForOpenScience/cas-overlay pull request #125
Opened 2018-08-07 18:57 UTC by cslzchen

## Ticket

No

## Purpose

Remove requirements for the header "REMOTE_USER" for SAML/SHIB login

The header "REMOTE_USER" is not required as an identifier for institution users. OSF and CAS rely on `username` to identify such  users. The method `notifyRemotePrincipalAuthenticated()` guarantees that `username` is provided. For most cases, it is either the `eppn` or `mail` attribute.

"REMOTE_USR" header is only available if the institution has provided any of the three attributes: ``eppn``, ``persistent-id`` or ``targeted-id``. For institutions that provides ``mail`` (or other attributes) as ``username``, the header does not exist.

## Changes

* For institutions that has an empty "REMOTE_USER" header, set `remoteUser` to `""`. Log the case as WARNING and do not throw an exception.
* Update the comments for SAML/Shibboleth-based institution login

## Side effects

No

## QA Notes

No

## Deployment Notes

No

2018-08-07 19:53 UTC, cslzchen reviewed
cc @icereval 

PR ready 🎆 . I will hot-fix this in soon.

2018-08-07 19:53 UTC, cslzchen commented on cas-server-support-osf/src/main/java/io/cos/cas/authentication/handler/support/OpenScienceFrameworkPrincipalFromRequestRemoteUserNonInteractiveCredentialsAction.java
> +                remoteUser = "";
If the header "REMOTE_USER" does not exit, log the incident and set `remoteUser` to the empty string.

2018-08-07 20:16 UTC, icereval submitted a review, later dismissed
Can you add to the PR a link and quote for the article referencing the justification for removing the Remote User check.

2018-08-08 00:19 UTC, icereval requested changes
After further discussion, lets keep this as a just in case check.

2018-08-16 13:51 UTC, cslzchen commented
Update: comments update only, no longer functional, rebase to target develop. Closing.

2018-08-16 13:51 UTC, closed without merging