[Feature] Institution Login for OKState University and Delegate Authentication to External CAS Server [#CAS-15][#OSF-7271]
CenterForOpenScience/cas-overlay pull request #42
Opened 2017-02-02 00:39 UTC by cslzchen

### Tickets and PRs:

- Replaces #30, #37 
- OSF PR: https://github.com/CenterForOpenScience/osf.io/pull/6754
- CAS Ticket: https://openscience.atlassian.net/browse/CAS-15
- OSF Ticket: https://openscience.atlassian.net/browse/OSF-7271

2017-03-09 20:00 UTC, cslzchen commented on cas-server-support-osf/src/main/java/io/cos/cas/authentication/handler/support/OpenScienceFrameworkPrincipalFromRequestRemoteUserNonInteractiveCredentialsAction.java
>          if (StringUtils.hasText(shibbolethSession)) {
Institution Login by External Shibboleth IDP.

2017-03-09 20:00 UTC, cslzchen commented on cas-server-support-osf/src/main/java/io/cos/cas/authentication/handler/support/OpenScienceFrameworkPrincipalFromRequestRemoteUserNonInteractiveCredentialsAction.java
> +        } else if (context.getFlowScope().get("authenticationDelegationProtocol") == PROTOCOL_CAS) {
Institution Login by External CAS IDP.

2017-03-09 20:00 UTC, cslzchen commented on cas-server-support-osf/src/main/java/io/cos/cas/authentication/handler/support/OpenScienceFrameworkPrincipalFromRequestRemoteUserNonInteractiveCredentialsAction.java
> +                principal = ticketGrantingTicket.getAuthentication().getPrincipal();
Retrieve the `principal` from `TGT` which contains authenticated institution user's information.

2017-03-09 20:00 UTC, cslzchen commented on cas-server-support-osf/src/main/java/io/cos/cas/authentication/handler/support/OpenScienceFrameworkPrincipalFromRequestRemoteUserNonInteractiveCredentialsAction.java
> +    private OpenScienceFrameworkCredential constructCredentialFromRemotePrincipal(
Update `credential.authenticationHeaders` which will be normalized with XML XSLT.
- `Shib-Identity-Provider`
- `uid`
- attributes in `principal`
  - OK State University
    - `mail` is mapped to `username` (they don't provide `eppn`)
    - `fullname` is mapped to `uid` (they don't provider `displayName`)
    - `sn` is mapped to `familyName`
    - `givenName` is mapped to `givenName`

2017-03-09 20:00 UTC, cslzchen commented on cas-server-support-osf/src/main/java/io/cos/cas/authentication/handler/support/OpenScienceFrameworkPrincipalFromRequestRemoteUserNonInteractiveCredentialsAction.java
> +                normalizedPayload = this.normalizeRemotePrincipal((this.constructCredentialFromRemotePrincipal(credential, principal)));
For CAS IDP, `credential` does not contain authenticated user's information yet. Call `constructCredentialFromRemotePrincipal` to update it with `principal` before normalization.

2017-03-09 20:00 UTC, cslzchen commented on cas-server-webapp/src/main/java/org/jasig/cas/support/pac4j/authentication/handler/support/ClientAuthenticationHandler.java
> +    protected HandlerResult createResult(final ClientCredential credentials, final UserProfile profile)
The default method creates a principal after successful authentication. The principal is created with the id that uses class name (e.g. `CacClient`), in which case we can not identify the client name (e.g. `okstate`). We override it to use the client name.

2017-03-09 20:00 UTC, cslzchen commented on cas-server-webapp/src/main/java/org/jasig/cas/support/pac4j/web/flow/ClientAction.java
> +                if (INSTITUTION_CLIENTS.contains(clientName)) {
After successfully authentication, all necessary information is already stored in the `principal` in the `TGT`. If we identify the client to be an institution client, the flow is intercepted and redirected to our institution login flow independent of the delegation protocol.

2017-03-09 20:00 UTC, cslzchen commented on cas-server-webapp/src/main/webapp/WEB-INF/webflow/login/login-webflow.xml
> +        <transition on="remote" to="remoteAuthenticate" />
As mentioned before, the spring config for intercepted flow for institution login.

2017-03-09 20:00 UTC, cslzchen commented on cas-server-webapp/src/main/webapp/WEB-INF/view/jsp/default/ui/casInstitutionLoginView.jsp
> +                login_url = "${okstateUrl}";
As mentioned before, dynamically build `login_url`.

2017-03-09 20:00 UTC, cslzchen commented on cas-server-support-osf/src/main/java/io/cos/cas/adaptors/postgres/handlers/OpenScienceFrameworkInstitutionHandler.java
> +                    institutionLogin.put(institution.getId(), institution.getName());
Login URLs using `pac4j` are built dynamically. This is why we set login_url to be the client_name for OK State University.

2017-04-04 20:02 UTC, cslzchen commented on cas-server-support-osf/src/main/java/io/cos/cas/adaptors/postgres/daos/OpenScienceFrameworkDaoImpl.java
> +                            + "where i.delegationProtocol is not empty and i.deleted = false",
`delegation_protocol` is used to determine whether an institution has login available, instead of `login_url`.

2017-04-06 21:54 UTC, icereval requested changes

2017-04-06 21:54 UTC, icereval commented on cas-server-webapp/src/main/java/org/jasig/cas/support/pac4j/web/flow/ClientAction.java
> +    public static final Set<String> INSTITUTION_CLIENTS = ImmutableSet.of(
institutions should not be hardcoded, should perform a database lookup

2017-04-07 19:02 UTC, cslzchen commented on cas-server-support-osf/src/main/java/io/cos/cas/adaptors/postgres/models/OpenScienceFrameworkInstitution.java
> +    public enum DelegationProtocols {
Use `enum` instead of hard-coded literal `String`.

2017-04-07 19:02 UTC, cslzchen commented on cas-server-webapp/src/main/java/org/jasig/cas/support/pac4j/authentication/handler/support/ClientAuthenticationHandler.java
> +    private final OpenScienceFrameworkInstitutionHandler institutionHandler;
Need an instance of `OpenScienceFrameworkInstitutionHandler` to access ` OpenScienceFrameworkInstitution` model and dao.

2017-04-07 19:02 UTC, cslzchen commented on cas-server-webapp/src/main/java/org/jasig/cas/support/pac4j/web/flow/ClientAction.java
> +    private final OpenScienceFrameworkInstitutionHandler institutionHandler;
Need an instance of `OpenScienceFrameworkInstitutionHandler` to access ` OpenScienceFrameworkInstitution` model and dao.

2017-04-07 19:02 UTC, cslzchen commented on cas-server-webapp/src/main/java/org/jasig/cas/support/pac4j/authentication/handler/support/ClientAuthenticationHandler.java
> +            if (this.institutionHandler.isDelegatedInstitutionLogin(clientName)) {
Identity clients that are also institution.

2017-04-07 19:02 UTC, cslzchen commented on cas-server-webapp/src/main/java/org/jasig/cas/support/pac4j/web/flow/ClientAction.java
> +                if (this.institutionHandler.isDelegatedInstitutionLogin(clientName)) {
Identify clients that are also institution. Intercept the flow and go to `remoteAuthenticate`.

2017-04-07 19:02 UTC, cslzchen commented on cas-server-support-osf/src/main/java/io/cos/cas/adaptors/postgres/models/OpenScienceFrameworkApiOauth2Application.java
> +    @Column(name ="_id", nullable = false, unique=true)
Stay consistent with the OSF database.

2017-04-07 19:30 UTC, cslzchen commented
After we enforce the `fullname` requirement, the test account for okstate can no longer sign in. If you see the following log/sentry message for API server, consider authentication successful.
```
[framework.sentry]  WARNING: Sentry called to log message, but is not active: Institution login failed: fullname required for user test.user14@okstate.edu from institution okstate
```

2017-04-12 21:17 UTC, icereval requested changes

2017-04-12 21:17 UTC, icereval commented on cas-server-webapp/src/main/java/org/jasig/cas/support/pac4j/authentication/handler/support/ClientAuthenticationHandler.java
> +     */
please add examples of the `clientName` cases

2017-04-12 21:17 UTC, icereval commented on cas-server-webapp/src/test/java/org.jasig.cas.support.pac4j/authentication.handler.support/ClientAuthenticationHandlerTests.java
> +/*
Add test to validate two factor auth w/ each provider.

2017-04-12 21:17 UTC, icereval commented on cas-server-support-osf/src/main/java/io/cos/cas/authentication/handler/support/OpenScienceFrameworkPrincipalFromRequestRemoteUserNonInteractiveCredentialsAction.java
> +        credential.getAuthenticationHeaders().put("Shib-Identity-Provider", institutionId);
Rename `getAuthenticationHeders` to a more general term like `getDelegationAttributes`.

Change to `Shib-Identity-Provider` to `Cas-Identity-Provider`.

Add `Delegation-Protocol` to `credential` for both CAS and SAML and append to normalization document xslt processor.

2017-04-12 21:17 UTC, icereval commented on cas-server-webapp/src/main/java/org/jasig/cas/support/pac4j/authentication/handler/support/ClientAuthenticationHandler.java
> +            } else if (clientName.startsWith("CasClient")) {
remove this case for now, we can dig into what we would like this to be named in the future

2017-04-12 21:17 UTC, icereval commented on cas-server-webapp/src/main/java/org/jasig/cas/support/pac4j/authentication/handler/support/ClientAuthenticationHandler.java
> +                id = clientName + '#' + profile.getId();
use standard naming convention w/ `Profile` designation at the end.

e.g. `id = clientName + "Profile#" + profile.getId();`

2017-04-12 21:17 UTC, icereval commented on cas-server-support-osf/src/main/java/io/cos/cas/adaptors/postgres/handlers/OpenScienceFrameworkInstitutionHandler.java
> +                    OpenScienceFrameworkInstitution.DelegationProtocols.SAML_SHIB.name())) {
in a future pr we should consider moving shibboleth url construction logic to the cas side

2017-04-12 21:17 UTC, icereval commented on cas-server-support-osf/src/main/java/io/cos/cas/authentication/handler/support/OpenScienceFrameworkPrincipalFromRequestRemoteUserNonInteractiveCredentialsAction.java
> +        // for institutions that do not release full name, set uid as their full name in "institution-auth.xsl"
???

2017-04-13 19:48 UTC, cslzchen reviewed
@icereval ready with several updates

2017-04-13 19:48 UTC, cslzchen commented on cas-server-support-osf/src/main/java/io/cos/cas/authentication/OpenScienceFrameworkCredential.java
> +    private String delegationProtocol;
Add `delegationProtocol` (above) and rename `authenticationHeaders` to `delegationAttributes` (below) for `OpenScienceFrameworkCredential`, where now there are four institution related properties:
- `remotePrincipal`
- `institutionId`
- `delegationProtocol`
- `delegationAttributes`

2017-04-13 19:48 UTC, cslzchen commented on cas-server-support-osf/src/main/java/io/cos/cas/authentication/handler/support/OpenScienceFrameworkPrincipalFromRequestRemoteUserNonInteractiveCredentialsAction.java
> +    public static final String PROTOCOL_CAS = OpenScienceFrameworkInstitution.DelegationProtocols.CAS_PAC4J.name();
Uses `enum` instead of literal `String` for `PROTOCOL_CAS` (above) and same for `PROTOCOL_SAML` (below).

2017-04-13 19:48 UTC, cslzchen commented on cas-server-support-osf/src/main/java/io/cos/cas/authentication/handler/support/OpenScienceFrameworkPrincipalFromRequestRemoteUserNonInteractiveCredentialsAction.java
> +            credential.getDelegationAttributes().put("Delegation-Protocol", PROTOCOL_SAML);
(Above) Add `Delegation-Protocol` to `delegationAttributes` to improve `xslt`.
(Below) Update `credential` with the newly introduced `delegationProtocol`.

2017-04-13 19:48 UTC, cslzchen commented on cas-server-support-osf/src/main/java/io/cos/cas/authentication/handler/support/OpenScienceFrameworkPrincipalFromRequestRemoteUserNonInteractiveCredentialsAction.java
> +        } else if (PROTOCOL_CAS.equals(credential.getDelegationProtocol())) {
From flow action `clientAction` to `remoteAuthenticate` during `CAS_PAC4J` institution login, the `credential` contains the protocol information and institution id.

2017-04-13 19:48 UTC, cslzchen commented on cas-server-support-osf/src/main/java/io/cos/cas/authentication/handler/support/OpenScienceFrameworkPrincipalFromRequestRemoteUserNonInteractiveCredentialsAction.java
> +    private OpenScienceFrameworkCredential constructCredentialFromRemotePrincipal(
Update `credential.delegationAttributes`:
- `Delegation-Protocol`: a control variable for XSLT to choose which type of transformation to apply.
- `Cas-Identity-Provider`: use `clientName` which is identical to `institutionId`
- `attributes` in `principal`
  - OK State University
    - `mail` is mapped to `username`
    - `sn` is mapped to `familyName`
    - `givenName` is mapped to `givenName`
- Refer to the `institutions-auth.xsl` I airdropped to you.

2017-04-13 19:48 UTC, cslzchen commented on cas-server-webapp/src/main/java/org/jasig/cas/support/pac4j/web/flow/ClientAction.java
> +                // for institution clients:
As commented below.

2017-04-13 19:48 UTC, cslzchen commented on cas-server-webapp/src/main/java/org/jasig/cas/support/pac4j/authentication/handler/support/ClientAuthenticationHandler.java
> +     * Note on customization:
The updated docstr with examples.

2017-04-13 20:59 UTC, cslzchen commented on cas-server-support-osf/src/main/java/io/cos/cas/adaptors/postgres/handlers/OpenScienceFrameworkInstitutionHandler.java
> +                = openScienceFrameworkDao.findOneInstitutionById(clientName.toLowerCase());
I think I misunderstood this before. Here is the `toLowerCase()` comparison for `clientName` as `institutionId`.

2017-04-17 03:15 UTC, icereval commented
Testing

1. master
2. new cas db
3. login w/ normal methods + oauth application
4. upgrade to pr
5. restart cas
6. verify methods remain logged in and you can access `/login` and api oauth endpoints w/ `Bearer <token>`

2017-04-17 03:33 UTC, icereval approved these changes

2017-04-17 21:06 UTC, cslzchen commented
@icereval local tests done, all passed

### `develop` (identical to `master` for CAS)

* New CAS Database
* Four Users:
  * NYU user, with 2FA on, logged in
  * ORCID user, with 2FA on, logged in
  * OSF user, with 2FA on, logged in
  * OSF master, with developer app, with a valid PAT, logged in
* OSF user authorizes the Master App and Master App receives the AT, can profile and act on behalf of OSF user

### `feature/okstate` upgrade

* Perform Upgrade
* CAS starts successfully
* All checks below are verified:
  * All four users' CAS page still logged in. (TGT is still valid)
  * All four users' OSF page still logged in.
  * Log all four users out and login again successfully with 2FA working.
  * Master user's PAT still works. (PAT is still valid)
  * Master user's developer app gets loaded in CAS.
  * Master App can still profile and and act on behalf of the user. (AT is still valid)
  * NYU and ORCID users successfully authorize Master App.
* OKState
  * User successfully logged in.
  * 2FA works as expected.

2017-04-17 22:43 UTC, merged