[HotFix] Fix Oauth Clients Revoking [No Ticket]
CenterForOpenScience/cas-overlay pull request #91
Opened 2017-11-17 14:55 UTC by cslzchen

N/A

2017-11-17 15:52 UTC, cslzchen reviewed
Ready for CR @icereval , thanks.

2017-11-17 15:52 UTC, cslzchen commented on cas-server-support-oauth/src/main/java/org/jasig/cas/support/oauth/CentralOAuthServiceImpl.java
> -            ticketRegistry.deleteTicket(token.getTicket().getId());
### This Issue
If there is more than one token, the second execution fails here. Here is a [link](https://github.com/apereo/cas/blob/4.1.x/cas-server-support-jdbc/src/main/java/org/jasig/cas/ticket/registry/JpaTicketRegistry.java#L96) to the failure code that throws the following error:
```
object references an unsaved transient instance - save the transient instance before flushing
```
Please note this happens for the access token below as well.

The first attempt is to  update our `AccessTokenImpl` to set `CascadeType.ALL` for its property `TicketGrantingTicket, which prevents the error but does not update the database.

2017-11-17 15:52 UTC, cslzchen commented on cas-server-support-oauth/src/main/java/org/jasig/cas/support/oauth/CentralOAuthServiceImpl.java
> +        ticketRegistry.deleteTicket(token.getTicket().getId());
### The Fix

The issue is fixed by only revoke one token at a time in the callee:
```java
CentralOAuthServiceImpl.revokeClientTokens
```
and move the for logic (and the service check as a side effect) to the caller:
```java
OAuth20RevokeClientTokensController. handleRequestInternal()
```
`revokeClientTokens()` returns `Boolean.TRUE` if all tokens are cleared and `Boolean.FASLE` if there is more to continue.

2017-11-17 15:52 UTC, cslzchen commented on cas-server-support-oauth/src/main/java/org/jasig/cas/support/oauth/web/OAuth20RevokeClientTokensController.java
> +        if (service == null || !service.getClientSecret().equals(clientSecret)) {
The service check is moved from `revokeClientTokens` to here.

2017-11-17 15:52 UTC, cslzchen commented on cas-server-support-oauth/src/main/java/org/jasig/cas/support/oauth/web/OAuth20RevokeClientTokensController.java
> +        for (int i = 0; i <= MAX_NUM_OF_ATTEMPTS; i++) {
Set a `MAX_NUM_OF_ATTEMPTS` in case some token and related tickets are locked. Raises `SC_INTERNAL_SERVER_ERROR` if the cap is reached.

2017-12-11 22:13 UTC, cslzchen commented on cas-server-support-oauth/src/main/java/org/jasig/cas/support/oauth/CentralOAuthServiceImpl.java
> -            ticketRegistry.deleteTicket(token.getTicket().getId());
Update, further investigation reveals that this is caused by the `@transcient` annotation [link](https://github.com/CenterForOpenScience/cas-overlay/blob/develop/cas-server-support-oauth/src/main/java/org/jasig/cas/support/oauth/token/AccessTokenImpl.java#L96):

```java
    @Transient
    public Ticket getTicket() {
        if (getType() == TokenType.OFFLINE) {
            return this.serviceTicket;
        }

        return this.ticketGrantingTicket;
    }
```

2017-12-13 16:48 UTC, icereval requested changes
Try to avoid the while loop behavior.

2018-01-29 21:14 UTC, cslzchen commented
PR closed and a better fix continues in https://github.com/CenterForOpenScience/cas-overlay/pull/95.

2018-01-29 21:14 UTC, closed without merging