[Fix] OAuth Revoke [SVCS-599]
CenterForOpenScience/cas-overlay pull request #95
Opened 2018-01-29 20:38 UTC by cslzchen

### Ticket

https://openscience.atlassian.net/browse/SVCS-599

### Purpose and Changes

Please refer to the ticket.

2018-01-29 20:54 UTC, cslzchen commented on cas-server-support-oauth/src/main/java/org/jasig/cas/support/oauth/token/AccessTokenImpl.java
> +@Access(AccessType.FIELD)
Explicitly set the default access type.

2018-01-29 21:12 UTC, cslzchen reviewed
Work In Progress. Need a few more tests before ready for CR.

2018-01-29 21:12 UTC, cslzchen commented on cas-server-support-oauth/src/main/java/org/jasig/cas/support/oauth/token/AccessTokenImpl.java
> -    @Transient
This is what was causing the error. Although this looks like a getter but there is no field for `ticket` at all. Not sure how `@Transient` apply to an non-getter.

2018-01-29 21:12 UTC, cslzchen commented on cas-server-support-oauth/src/main/java/org/jasig/cas/support/oauth/token/AccessTokenImpl.java
> +@Access(AccessType.FIELD)
Explicitly set the default access type.

2018-01-30 01:33 UTC, icereval commented
:+1:

2018-01-30 15:08 UTC, cslzchen reviewed
~~The code is tested locally with full OAuth flow working as expected. Ready for review @icereval .~~

- Revoking clients with ~~multiple access tokens and refresh tokens~~ one refresh token and multiple access tokens obtained from that refresh token succeeds.
- Without `@Transient`, `.getTicket()` acts like a helper/utility method for all related classes and doesn't do anything else. This is the expected behavior.
- [x] Not sure why we had `@Transient` in the first place (commit message does not help). Please double check before approving/merging.

2018-02-22 15:20 UTC, icereval approved these changes
LGTM

2018-02-22 18:31 UTC, cslzchen commented
Update: further test reveals a few more issues. Please refer to the ticket for more detail

2018-02-23 20:24 UTC, icereval requested changes
Holding on merge for further testing.

2018-02-28 04:25 UTC, cslzchen reviewed
Move to RTM after another round of full test and before/after verification.

2018-02-28 04:25 UTC, cslzchen commented on cas-server-support-oauth/src/main/java/org/jasig/cas/support/oauth/CentralOAuthService.java
> +    TokenRegistry getTokenRegistry();
Expose the `tokenRegistry` in `CentralOAuthService` to `OAuth20RevokeClientTokensController`.

2018-02-28 04:25 UTC, cslzchen commented on cas-server-support-oauth/src/main/java/org/jasig/cas/support/oauth/CentralOAuthService.java
> +//    Boolean revokeClientTokens(String clientId, String clientSecret);
Deprecating the `revokeClientTokens()` which is no longer used.
For future references, I decide to keep it in the code base commented out for now and for a while.

2018-02-28 04:25 UTC, cslzchen commented on cas-server-support-oauth/src/main/java/org/jasig/cas/support/oauth/CentralOAuthServiceImpl.java
> +//    public Boolean revokeClientTokens(final String clientId, final String clientSecret) {
Similarly to the interface, the implementation of `revokeClientTokens()` is deprecated.

2018-02-28 04:25 UTC, cslzchen commented on cas-server-support-oauth/src/main/java/org/jasig/cas/support/oauth/web/OAuth20RevokeClientTokensController.java
> +        TokenRegistry tokenRegistry = centralOAuthService.getTokenRegistry();
Use the exposed `tokenRegistry` to get a list of all tokens and remove them using `for` loops.
No more bad `while` loops.

2018-02-28 05:45 UTC, cslzchen commented on cas-server-support-oauth/src/main/java/org/jasig/cas/support/oauth/CentralOAuthService.java
> +    TokenRegistry getTokenRegistry();
Update: a better interface design should hide the token registry but return a list of available tokens associated with the client.

2018-02-28 16:14 UTC, cslzchen reviewed
PR ready again 🔥 🔥 

- Tested locally with three different scenarios. All passed Postman tests and further verified inside the database.
- Before/After test for DB passes as well. (There is no actual model change.)

Please refer to the ticket for more detailed test configuration and results.

2018-02-28 16:14 UTC, cslzchen commented on cas-server-support-oauth/src/main/java/org/jasig/cas/support/oauth/CentralOAuthService.java
> +     void revokeClientTokens(String clientId, String clientSecret);
Deprecate `revokeClientTokens()`.

2018-02-28 16:14 UTC, cslzchen commented on cas-server-support-oauth/src/main/java/org/jasig/cas/support/oauth/CentralOAuthServiceImpl.java
> +        throw new UnsupportedOperationException("revokeClientTokens are deprecated and should not be used");
Deprecate the implementation of `revokeClientToken()`.

2018-02-28 16:14 UTC, cslzchen commented on cas-server-support-oauth/src/main/java/org/jasig/cas/support/oauth/token/RefreshTokenImpl.java
> +@Access(AccessType.FIELD)
Explicitly set the default access type for both refresh and access token.

2018-02-28 16:14 UTC, cslzchen commented on cas-server-support-oauth/src/main/java/org/jasig/cas/support/oauth/web/OAuth20RevokeClientTokensController.java
> -        if (!centralOAuthService.revokeClientTokens(clientId, clientSecret)) {
The functionality of `revokeClientTokens()` are removed and directly handled by the controller here in `OAuth20RevokeClientTokensController. handleRequestInternal()`. Please refer to the code below and the three following comments

2018-02-28 16:14 UTC, cslzchen commented on cas-server-support-oauth/src/main/java/org/jasig/cas/support/oauth/web/OAuth20RevokeClientTokensController.java
> +        if (service == null || !service.getClientSecret().equals(clientSecret)) {
Validate service first.

2018-02-28 16:14 UTC, cslzchen commented on cas-server-support-oauth/src/main/java/org/jasig/cas/support/oauth/web/OAuth20RevokeClientTokensController.java
> +        final Collection<RefreshToken> refreshTokens = centralOAuthService.getClientRefreshTokens(clientId);
Remove all refresh tokens.

2018-02-28 16:14 UTC, cslzchen commented on cas-server-support-oauth/src/main/java/org/jasig/cas/support/oauth/CentralOAuthService.java
> +    Collection<RefreshToken> getClientRefreshTokens(String clientId);
`CentralOauthService` now exposes the refresh token list of a specified client to `OAuth20RevokeClientTokensController`. Same for the access token list below.

2018-02-28 16:14 UTC, cslzchen commented on cas-server-support-oauth/src/main/java/org/jasig/cas/support/oauth/web/OAuth20RevokeClientTokensController.java
> +        final Collection<AccessToken> accessTokens = centralOAuthService.getClientAccessTokens(clientId);
Remove all access tokens.

2018-03-02 02:48 UTC, merged

2018-03-02 02:49 UTC, cslzchen reviewed
cc @icereval , I did another round of local test just now and all look good. Merged 🎆!